<?php
/**
 * moOde audio player (C) 2014 Tim Curtis
 * http://moodeaudio.org
 *
 * metaspot-plugin-start.php
 * 
 * Starts the needed services for the metadata plugin
 *
 */

define('SQLDB', 'sqlite:/var/local/www/db/moode-sqlite3.db');
define('SQLDB_PATH', '/var/local/www/db/moode-sqlite3.db');
define('METASPOT_LOG', '/var/log/metaspot-plugin-start.log');

// Debug message logger
function debugLog($msg, $mode = 'a') {
	$fh = fopen(METASPOT_LOG, $mode);
	fwrite($fh, date('Ymd His ') . $msg . "\n");
	fclose($fh);
}

debugLog("#########################################");
debugLog("metaspot-plugin-start v0.1");

# TODO: Check sudo
#

# Usage:
# 
$options = getopt("ab:c:d:n:p:v:");
// var_dump($options);

# Kill previous daemons
debugLog("metaspot-plugin-start - Kill started vollibrespot");
exec('sudo killall vollibrespot 2>&1 &', $output);

debugLog("metaspot-plugin-start - Kill started metaspot-plugin-daemon");
// sysCmd('kill $(ps aux | grep \'[p]hp /var/www/inc\'| awk \'{print $2}\')');
# This works from the command line: sudo kill $(ps aux | grep '[p]hp /var/www/inc/metaspot-plugin-daemon' | awk '{print $2}')
exec('sudo kill $(ps aux | grep \'[p]hp /var/www/inc/metaspot-plugin-daemon\'| awk \'{print $2}\') 2>&1 &', $output);

$initial_volume = 25;
if (isset($options['v'])) {
  $initial_volume = $options['v'];
}
$bitrate = 160;
if (isset($options['b'])) {
  $bitrate = $options['b'];
}
$deviceName = "Moode Spotify";
if (isset($options['n'])) {
  $deviceName = $options['n'];
}
$device = "plughw:1";
if (isset($options['d'])) {
  $device = $options['d'];
}
$volumeCtrl = "log";
if (isset($options['c'])) {
  $volumeCtrl = $options['c'];
}
$enableVolumeNormalization = false;
$normalisationPregain = 3;
if (isset($options['p'])) {
  $normalisationPregain = $options['p'];
  $enableVolumeNormalization = true;
}
$autoplay = false;
if (isset($options['a'])) {
  $autoplay = true;
}

debugLog('metaspot-plugin-start - Generate Vollibrespot config file');
$fh = fopen('/tmp/vollibrespot.toml', 'w');
$data  = "#########################################\n";
$data .= "# This file is automatically generated by\n";
$data .= "# metaspot-plugin-start.php.\n";
$data .= "#########################################\n\n";
$data  .= "[Authentication]\n";
$data  .= "device-name = '" . $deviceName . "'\n";
$data  .= "[Playback]\n";
$data  .= "bitrate = " . $bitrate . "\n";
$data  .= "volume-ctrl = '" . $volumeCtrl . "'\n";
if ($enableVolumeNormalization) {
  $data  .= "enable-volume-normalisation = true\n";
  $data  .= "normalisation-pregain = " . $normalisationPregain . "\n";
} else {
  $data  .= "enable-volume-normalisation = false\n";
  $data  .= "normalisation-pregain = " . $normalisationPregain . "\n";
}
if ($autoplay) {
  $data  .= "autoplay = true\n";
}
$data  .= "[Output]\n";
$data  .= "device = '" . $device . "'\n";
$data  .= "initial_volume = " . $initial_volume . "\n";
$data  .= "backend = 'alsa'\n";
$data  .= "[Misc]\n";
$data  .= "disable-audio-cache = true\n";
$data  .= "cache-location = '/var/local/www/spotify_cache'\n";
fwrite($fh, $data);
fclose($fh);

// TODO: check that vollibrespot & start-metaspot.php exists
$cmd = 'vollibrespot' .
  ' -c /tmp/vollibrespot.toml' .
  ' --verbose';
//  ' 2>&1 > /var/log/vollibrespot.log &';
$outputfile = '/var/log/vollibrespot.log';
$pidfile = '/var/log/vollibrespot.pid';
$cmdline = sprintf("%s > %s 2>&1 & echo $! >> %s", $cmd, $outputfile, $pidfile);
debugLog('metaspot-plugin-start: (' . $cmdline . ')');
exec($cmdline);

// Start process that reads udp metadata and executes a url
$cmd2 = 'php /var/www/inc/metaspot-plugin-daemon.php';
$outputfile2 = '/var/log/metaspot-plugin.log';
$pidfile2 = '/var/log/metaspot-plugin-daemon.pid';
$cmdline2 = sprintf("%s > %s 2>&1 & echo $! >> %s", $cmd2, $outputfile2, $pidfile2);
debugLog('metaspot-plugin-start: (' . $cmdline2 . ')');  
exec($cmdline2);

