<?php
/**
 * moOde audio player (C) 2014 Tim Curtis
 * http://moodeaudio.org
 *
 * metaspot-plugin-start.php
 * 
 * Starts the needed services for the metadata plugin
 *
 */

define('SQLDB', 'sqlite:/var/local/www/db/moode-sqlite3.db');
define('SQLDB_PATH', '/var/local/www/db/moode-sqlite3.db');
define('METASPOT_LOG', '/var/log/metaspot-plugin-start.log');

// Debug message logger
function debugLog($msg, $mode = 'a') {
	$fh = fopen(METASPOT_LOG, $mode);
	fwrite($fh, date('Ymd His ') . $msg . "\n");
	fclose($fh);
}

debugLog("#########################################");
debugLog("metaspot-plugin-start v0.1");

# TODO: Check sudo
#

# Usage:
# 
$options = getopt("ab:c:d:n:p:v:");
var_dump($options);

$initial_volume = 25;
if (isset($options['v'])) {
  $initial_volume = $options['v'];
}

debugLog('metaspot-plugin-start: Using Vollibrespot');
$fh = fopen('/tmp/vollibrespot.toml', 'w');
$data  = "#########################################\n";
$data .= "# This file is automatically generated by\n";
$data .= "# metaspot-plugin-start.php.\n";
$data .= "#########################################\n\n";
$data  .= "[Authentication]\n";
$data  .= "device-name = '" . $options['n'] . "'\n";
$data  .= "[Playback]\n";
$data  .= "bitrate = " . $options['b'] . "\n";
$data  .= "volume-ctrl = '" . $options['c'] . "'\n";
if (isset($options['p'])) {
  $data  .= "enable-volume-normalisation = '" . $initial_volume . "'\n";
  $data  .= "normalisation-pregain = '" . $options['p'] . "'\n";
}
if (isset($options['a'])) {
  $data  .= "autoplay = true\n";
}
$data  .= "[Output]\n";
$data  .= "device = '" . $options['d'] . "'\n";
$data  .= "initial_volume = " . $initial_volume . "\n";
$data  .= "backend = 'alsa'\n";
$data  .= "[Misc]\n";
$data  .= "disable-audio-cache = true\n";
$data  .= "cache-location = '/var/local/www/spotify_cache'\n";
fwrite($fh, $data);
fclose($fh);

// TODO: check that vollibrespot & start-metaspot.php exists
$outputfile = '/var/log/vollibrespot.log';
$pidfile = '/var/log/vollibrespot.pid';
$cmd = 'vollibrespot' .
  ' -c /tmp/vollibrespot.toml' .
  ' --verbose';
//  ' 2>&1 > /var/log/vollibrespot.log &';
debugLog('metaspot-plugin-start: (' . $cmd . ')');
exec(sprintf("%s > %s 2>&1 & echo $! >> %s", $cmd, $outputfile, $pidfile));

// Start process that reads udp metadata and executes a url
$cmd2 = 'php /var/www/inc/metaspot-plugin-daemon.php';
$outputfile2 = '/var/log/metaspot-plugin.log';
$pidfile2 = '/var/log/metaspot-plugin-daemon.pid';
$cmdline2 = sprintf("%s > %s 2>&1 & echo $! >> %s", $cmd2, $outputfile2, $pidfile2);
debugLog('metaspot-plugin-start: (' . $cmdline2 . ')');  
exec($cmdline2);

